### ISSUE TITLE
Changement du format des instances

### ISSUE THREAD

**Issue by laowantong** [pagination-problem/tree_structure#1]
@SarahMinich 
Le premier travail à faire est d'assainir les entrées-sorties en optant pour des formats qui ont une correspondance directe avec les structures de données utilisées. J'ai écrit un script qui convertit ton ancien format pour les instances :

```json
{
 "tiles": [
  "[N1, N2, N5, N10]",
  "[N1, N2, N5, N11]",
  "[N1, N3, N7, N14]",
  "[N1, N2, N4, N9]",
  "[N1, N3, N7, N15]"
 ],
 "symbols": [
  "[N1 - 0]",
  "[N2 - 5]",
  "[N3 - 3]",
  "[N4 - 1]",
  "[N5 - 2]",
  "[N7 - 6]",
  "[N9 - 2]",
  "[N10 - 1]",
  "[N11 - 4]",
  "[N14 - 3]",
  "[N15 - 5]"
 ],
 "height": 3,
 "max_symbol_size": 9,
 "opt_value": null,
 "opt_tiles_m1": [],
 "symbols_on_m1": [],
 "opt_tiles_m2": [],
 "symbols_on_m2": []
}
```

En ceci :

```json
{
  "height": 3,
  "symbol_size_bound": 9,
  "opt_value": null,
  "opt_tiles_m1": [],
  "symbols_on_m1": [],
  "opt_tiles_m2": [],
  "symbols_on_m2": [],
  "symbol_indexes": [1, 2, 3, 4, 5, 7, 9, 10, 11, 14, 15],
  "symbol_sizes": [0, 5, 3, 1, 2, 6, 2, 1, 4, 3, 5],
  "tiles": [
    [1, 2, 5, 10],
    [1, 2, 5, 11],
    [1, 3, 7, 14],
    [1, 2, 4, 9],
    [1, 3, 7, 15]
  ]
}
```

Au passage, j'ai remplacé la clé `"max_symbol_size"` par `"symbol_size_bound`".

Ce script fait appel à une bibliothèque d'expressions régulières avancées :

```
pip install regex
```

J'ai appliqué la conversion à tous les fichiers du répertoire `inputs`, ai déplacé celui-ci dans le répertoire `deprecated` et stocké les fichiers convertis dans un nouveau répertoire `input` (sans s).

**Comment by SarahMinich** [comment]
C'est noté !
Juste, pourquoi pas de 's' dans le nom du dossier ?

**Comment by laowantong** [comment]
Aucune importance, c'est juste mon habitude, et ça me permet de faire la différence entre ancien et nouveau dossier.

**Comment by SarahMinich** [comment]
D'accord !
