### ISSUE TITLE
Cohabitation des deux façons de générer des instances

### ISSUE THREAD

**Issue by SarahMinich** [pagination-problem/tree_structure#22]
Dans le commit e63be86, j'ai ajouté un fichier `new_instance_generation.py` (et le fichier de test qui va avec).
Je sais qu'il y a énormément de code qui est commun avec le code que écrit par Aristide dans `instance_generation.py` mais je ne sais pas comment faire cohabiter correctement les deux façons de faire au sein du même fichier car je n'arrive pas très bien à comprendre comment fonctionne la fonction `__call__`.

Je crée donc une issue pour signaler ce problème. Le programme reste utilisable mais c'est moche

**Comment by laowantong** [comment]
`__call__` permet d'appeler une instance de classe comme si c'était une fonction.

https://stackoverflow.com/questions/44178162/call-method-of-type-class

En l'occurrence, ce n'est pas la peine de faire « cohabiter les deux façons de faire ». Tu rajoutes simplement les nouvelles infos dans toutes les instances existantes et futures. Il n'y a pas de pénalité rédhibitoire au niveau performance, et si un solveur donné n'utilise pas les infos supplémentaires, ça n'a aucune importance.

Signale-moi quand ton code:

- passera les tests existants, modifiés si besoin;
- passera les nouveaux tests que tu as écrits pour vérifier les nouvelles fonctionnalités;
- aura une seule occurrence du code modifié. En créant des copies genre `new_`, non seulement tu ne tires pas profit du contrôle de versions, mais tu l'empêches activement de fonctionner correctement. Il devient impossible d'utiliser Git pour comparer les deux versions du code. Encore une fois, le contrôle de versions est justement censé t'éviter de faire des duplications. Tu peux à la limite le faire très temporairement sur ta machine, par exemple pour ouvrir deux copies côte à côte. Mais il ne faut jamais aller jusqu'au commit.

Je pourrai alors le lire et voir directement ce que tu as ajouté.
