### ISSUE TITLE
Problème d'import d'un autre fichier python

### ISSUE THREAD

**Issue by SarahMinich** [pagination-problem/tree_structure#3]
J'ai commencé à écrire les tests pour le fptas dans test_fptas.py (cf le [commit](a066462583b631fe04b2670ba8a4b35bb37491b9)) mais je rencontre un problème on ne peut plus bête... J'ai voulu placer le fichier de tests dans le dossier tests mais quand je le fais, j'ai une erreur quand j'essaye 

> import tools

car ce fichier se trouve un étage plus haut dans l'arborescence... J'ai essayé de mettre en place les deux solutions qui reviennent souvent sur internet (notamment [ici](https://stackoverflow.com/questions/4383571/importing-files-from-different-folder)) mais ça ne marche pas.

J'ai donc temporairement laissé le fichier test_fptas.py dans le dossier général pour pouvoir continuer à développer et je le déplacerai dès que j'aurai une solution.

**Comment by laowantong** [comment]
C'est un truc très pénible avec Python, oui. Une solution est d'ajouter explicitement les chemins souhaités. C'est ce que j'ai fait dans `context.py`, regarde les importations dans les tests que j'ai écrits.

**Comment by laowantong** [comment]
Ton premier lien est mort.

**Comment by SarahMinich** [comment]
J'avais vu que vous aviez ajouté un fichier 

> context.py 

mais je n'avais pas très bien compris ce qu'il faisait. Mais ça a l'air de marcher maintenant donc merci beaucoup !

**Comment by SarahMinich** [comment]
Je ne comprends pas pourquoi mon lien vers le commit en question ne fonctionne pas, j'ai vérifié plusieurs fois le numéro du commit et je mets le bon...
