### ISSUE TITLE
La fonctionnalité de traitement unique des instances ne fonctionne plus

### ISSUE THREAD

**Issue by SarahMinich** [pagination-problem/tree_structure#4]
Pour faciliter les tests sur de nombreuses instances, vous aviez ajouté quelques lignes de code pour vérifier si une instance avait déjà été traitée ou pas. Ainsi, je pouvais arrêter l'exécution du programme et la reprendre plus tard sur le même groupe d'instances en ré-excutant la même ligne de commande et il ne traitait que les instances qu'il n'avait pas déjà traitées.

Ces lignes de code sont dans run_fptas.py à partir de la ligne 34 (je sais que j'utilise les mauvaises balises mais si je prends celles dédiées à la citation de code, il met tout sur la même ligne et c'est illisible je trouve).
> 
> output_path = Path(f"{output_dir}/{output_prefix}_{tile_count}-tiles_{epsilon}-epsilon.txt")
> already_processed = set()
> if not log and output_path.is_file():
>     for line in output_path.read_text().split("\n"):
>         already_processed.add(line.partition(";")[0] + ".json")
>

**Comment by laowantong** [comment]
https://github.com/pagination-problem/tree_structure/blob/5ea6b730fc67ab7c4c941977c4df223b55b70975/run_fptas.py#L32-L36

Ou bien :

```python
output_path = Path(f"{output_dir}/{output_prefix}_{tile_count}-tiles_{epsilon}-epsilon.txt")
already_processed = set()
if not log and output_path.is_file():
    for line in output_path.read_text().split("\n"):
        already_processed.add(line.partition(";")[0] + ".json")
```

En quoi c'est moins lisible ? L'indentation est significative en Python.

Je regarderai ça plus tard.

**Comment by SarahMinich** [comment]
Justement, il ne fait pas ça quand j'utilise les balises de code, c'est bien mon problème.

Voilà ce que ça donne : 
EDIT : C'est ok maintenant.
```
output_path = Path(f"{output_dir}/{output_prefix}{tile_count}-tiles{epsilon}-epsilon.txt")
already_processed = set()
if not log and output_path.is_file():
    for line in output_path.read_text().split("\n"):
    already_processed.add(line.partition(";")[0] + ".json")
```

**Comment by laowantong** [comment]
https://fr.wikipedia.org/wiki/Markdown
