### ISSUE TITLE
Random tree generation

### ISSUE THREAD

**Issue by SarahMinich** [pagination-problem/tree_structure#5]
Imed voudrait que je mette en place une génération aléatoire d'arbres pour pouvoir tester de futures heuristiques et confirmer des hypothèses de travail en se basant sur cette représentation d'arbres (https://fr.wikipedia.org/wiki/Codage_de_Pr%C3%BCfer).

Je me suis dit qu'avant de commencer à coder, j'allais vous en parler, comme ça je suivrai dès le début vos conventions et votre façon de faire.

J'ai créé un Project avec exactement ce nom et cette description mais je crois que j'ai mal compris à quoi servaient les projets alors je crée également une Issue pour vous demander votre avis.

**Comment by laowantong** [comment]
Remarque : tester, versionner, etc., ce ne sont pas « mes » conventions, ce sont « les » conventions. Tu n'apprends pas ça pour me faire plaisir, mais pour compléter ta formation.

**Comment by laowantong** [comment]
Regarde ce genre de chose avant de réinventer la roue : https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.tree.coding.from_prufer_sequence.html

**Comment by SarahMinich** [comment]
J'avais trouvé des implémentations en C#, Java et C++ mais rien en Python, merci !
