### ISSUE TITLE
Problème de notification

### ISSUE THREAD

**Issue by SarahMinich** [pagination-problem/tree_structure#7]
Il n'y avait qu'un endroit dans les réglages de GitHub où mon adresse par défaut n'était pas la bonne et c'est pour ce répertoire. Il y avait donc peut-être un conflit entre les deux possibilités ?

![image](https://user-images.githubusercontent.com/53268501/76307090-6d99d200-62c8-11ea-8c9e-5497a174bb8b.png)

En tout cas, je viens de re-changer, pouvez-vous répondre à ce message pour voir si je reçois les notifications ?

**Comment by laowantong** [comment]
test

**Comment by laowantong** [comment]
https://github.com/settings/notifications

**Comment by SarahMinich** [comment]
C'est ok !
(Et c'est effectivement dans cette page tout en bas que les adresses différaient).
